### ISSUE TITLE
can not import computers.json to old bloodhound 4.3.1

### ISSUE THREAD

**Issue by enj5oy** [coffeegist/bofhound#2]
I use pyldapsearch with filter Objectclass=computers.
neo4j community version 4.3.13
Then i run bofhound output is computers.json file.
I open Bloodhound 4.1.0 release is Feb 10 2022
I can not upload computers.json file to bloodhound
![bloodhound_issue](https://github.com/coffeegist/bofhound/assets/143943083/50423ece-f25c-429d-ad07-a7fabb7c44f7)

This behavior start after commit "update JSON specs for BH CE (v5.0.0)". But bloodhound-CE in beta test, do not include queries etc. Can you please add functionality for convert computers json to old format for import to bloodhound 4.3.13 or support flag --old-bh.
Thanks for your work!

**Comment by Tw1sm** [comment]
Thanks for moving the issue here 😄 if you want to use Legacy BlooudHound instead of the community edition, you can use `bofhound <= 0.2.0`. Version 0.2.1 and newer will support CE.

We still need to bring the old tagged releases to this repo, but if you installed from PyPI, you can grab the old version with `pip3 install bofhound==0.2.0`. You might also want to update your BloodHound to v4.3.1 instead of v4.1.0.
